services:
  postgres:
    image: postgres:alpine3.20
    restart: always
    ports:
      - 5432:5432
    networks:
      - reactive-apps
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_USER}
      - POSTGRES_USER=${POSTGRES_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    ports:
      - 27017:27017
    networks:
      - reactive-apps
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_USER}
    volumes:
      - mongo:/data/db

networks:
  reactive-apps:

volumes:
  postgres:
  mongo: